//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laitehallinta2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logi
    {
        public int LogiID { get; set; }
        public Nullable<int> SijaintiID { get; set; }
        public Nullable<int> PaikkaID { get; set; }
        public Nullable<int> KirjaajaID { get; set; }
        public Nullable<System.DateTime> Kirjattusisään { get; set; }
        public Nullable<int> HenkiloID { get; set; }
        public Nullable<int> LaiteID { get; set; }
        public Nullable<int> TilaID { get; set; }
    
        public virtual Henkilot Henkilot { get; set; }
        public virtual Laitteet Laitteet { get; set; }
        public virtual Tilat Tilat { get; set; }
    }
}
